services:
  - type: web
    name: google-calendar-fastapi
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /app/credentials/calendarbookingagent-465016-f19347722100.json
      - key: GROQ_API_KEY
        sync: false
      - key: LANGCHAIN_API_KEY
        sync: false
    autoDeploy: true
